version: '3'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
  script:
    build: ./script
    #restart: always
    depends_on:
      - mysql
    volumes:
      - /script/__pycache__
      - ./script:/script
    environment:
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    