version: '3'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
  script:
    build: ./script
    restart: always
    depends_on:
      - mysql
    volumes:
      - /script/__pycache__
      - ./script:/script
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    