name: Run Tests


on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"

env:
  python_version: '3.12'

jobs:
  db_test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      packages: write

    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version}}

      - name: Install python dependencies
        run: |
          pip install mysql-connector-python pytest pytest-cov

      - name: Test with pytest
        run: |
          pytest -v --cov-report=html --cov=script

      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: htmlcov/
        if: ${{ always() }}
