name: Run Tests


on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"

env:
  python_version: '3.12'

jobs:
  db_test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version}}

      - name: Install python dependencies
        run: |
          pip install mysql-connector-python
          
      - name: Test app
        run: |
          pytest -v