name: Run Tests


on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"

env:
  python_version: '3.12'

jobs:
  db_test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      packages: write

    services:
      mysql:
        image: mysql
        env:
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version}}

      - name: Install python dependencies
        run: |
          pip install mysql-connector-python pytest pytest-cov

      - name: Test with pytest
        run: |
          pytest --doctest-modules --junitxml=pytest.xml --cov-report=term-missing:skip-covered > pytest-coverage.txt

      # - name: Upload pytest test results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: pytest-results
      #     path: test-results.xml
      #   if: ${{ always() }}



      - name: Pytest coverage comment
        if: ${{ github.ref == 'refs/heads/main' }}
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-coverage-path: pytest-coverage.txt
  
      - name: Update Readme with Coverage Html
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "${{ steps.coverageComment.outputs.coverageHtml }}" > ./README.md
          echo "${{ steps.coverageComment.outputs.summaryReport}}" >> ./README.md
  
      - name: Commit & Push changes to Readme
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions-js/push@master
        with:
          message: Update coverage on Readme
          github_token: ${{ secrets.GITHUB_TOKEN }}